### ISSUE TITLE
A link error occurred while compiling the my program.

### ISSUE THREAD

**Issue by 739304278** [log4cplus/log4cplus#584] opened 2023-05-06 03:54 UTC
Hello, I compiled the static library using version 2.1.0 release and used it. A link error occurred while compiling the my program.

Debugging found that the exception.cxx file was not added to the Source Files of the msvc14/log4cplus.sln project (log4cplus and log4cplusS projects).

Causing link errors during program usage

```
1>loglog.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl log4cplus::exception::exception(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &)" (??0exception@log4cplus@@QEAA@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z)，函数 "private: void __cdecl log4cplus::helpers::LogLog::logging_worker<wchar_t const *>(class std::basic_ostream<wchar_t,struct std::char_traits<wchar_t> > &,bool (__cdecl log4cplus::helpers::LogLog::*)(void)const ,wchar_t const *,wchar_t const * const &,bool)const " (??$logging_worker@PEB_W@LogLog@helpers@log4cplus@@AEBAXAEAV?$basic_ostream@_WU?$char_traits@_W@std@@@std@@P8012@EBA_NXZPEB_WAEBQEB_W_N@Z) 中引用了该符号
1>loglog.obj : error LNK2001: 无法解析的外部符号 "public: __cdecl log4cplus::exception::exception(class log4cplus::exception const &)" (??0exception@log4cplus@@QEAA@AEBV01@@Z)
1>loglog.obj : error LNK2001: 无法解析的外部符号 "public: virtual __cdecl log4cplus::exception::~exception(void)" (??1exception@log4cplus@@UEAA@XZ)
```

 - version: log4cplus-2.1.0
 - operating system, CPU, bitness: Win11 x64 
 - `configure` script, or CMake, etc., flags and settings:  Unicode
 - flags and settings used by your application: 
 - compiler and its version: Visual Studio 2022 (v143)  SDK:10.0.22000.0

**Comment by chenliangabc** [comment] 2023-09-23 04:49
Has this problem been solved?

**Comment by wilx** [comment] 2023-09-23 08:44
The problem is I don't have the old Visual Studio anymore. Can you use the CMake project to build log4cplus for you?

**Comment by wilx** [comment] 2023-09-25 11:08
Please test the 2.1.x branch. I have committed a fix. Re-open this issue if necessary.

**Comment by wilx** [comment] 2023-10-02 19:13
I forgot to add the .cxx file, too. :man_facepalming:

**Closed** 2023-10-03 10:26 UTC
Labels: bug
