### ISSUE TITLE
VS2015 build failing with C1001 and LNK1000 errors

### ISSUE THREAD

**Issue by rspydir** [log4cplus/log4cplus#235] opened 2017-04-04 19:27 UTC
I'd like to use log4cplus in a Windows app, but I'm have problems creating a release

I downloaded the source and opened msvc14/log4cplus.sln with VS2015 Professional

Debug mode builds fine, although I had to use 'Retarget SDK Version' to Windows 10 SDK on each project to get it to build

Release mode results in an error:
CS1001: An internal error has occurred in the compiler
LNK1000: Internal error during IMAGE::Pass1 (in file appender.obj)

My environment is:
Windows 10 Profesional
VS2015 14.0.254200.10 Update 3
Windows 10 SDK 10.0.14393.795

**Comment by gadh** [comment] 2017-04-04 19:57
i was able to compile in VS2015 using the 1.2.1-rc-1 version and the msvc10 project with no problems, debug/release flavors

**Comment by wilx** [comment] 2017-04-05 11:55
> (...) I had to use 'Retarget SDK Version' to Windows 10 SDK on each project to get it to build

You can change project properties en masse in the Property Manager tab, you do not have to do it manually one by one.

I have retargetted all of them to 10.0.14393.0, which is the biggest version I seem to have available here. I could not reproduce the issue.

My environment is Microsoft Visual Studio Enterprise 2015 Version 14.0.25431.01 Update 3. 

It is either a bug in the specific compiler that you are using or a transient issue that could be fixed by cleaning up the source tree and rebuilding. I am afraid I cannot have any better advice at this point.

**Comment by wilx** [comment] 2017-07-09 12:22
I was not able to reproduce this. I am closing this issue.

**Closed by wilx** 2017-07-09 12:22 UTC
Labels: invalid
