### ISSUE TITLE
Log4cplus cannot output Chinese

### ISSUE THREAD

**Issue by atu5554** [log4cplus/log4cplus#306] opened 2018-04-11 09:45 UTC
I set up log4cplus Unicode and MTD, just like my project。
I tried

```cpp
std::locale::global(std::locale("chs"));
std::locale lc("chs");
pRollingFileAppender->imbue(lc);
```

My environment: vs2015 ,log4cplus-1.2.1; MFC project

**Comment by wilx** [comment] 2018-04-11 11:05
`chs` does not looks like a valid Chinese locale, or any locale. Try `zh-CN` or some such instead.

**Comment by atu5554** [comment] 2018-04-13 01:01
I use GBK, zh_CN.UTF-8,  zh_CN,  zh_CN.Simplified. An exception will occur “std::runtime_error” Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  
I use log4cplusD.dll. log4cplusD.lib。 Build prompt “You are not using DLL C run time library.You must call log4cplus::initialize() once before you use any other log4cplus API.”

**Comment by atu5554** [comment] 2018-04-13 01:12
#include "stdafx.h"
#include<string>
#include "log.h"

Logger Log::logger = log4cplus::Logger::getInstance(LOG4CPLUS_TEXT("main_log"));

Log::Log()
{
}

Log::~Log()
{

}
Log& Log::instance()
{
	std::locale mylocale("zh_CN");
	std::cout.imbue(mylocale);
	log4cplus::initialize();
	static Log log;
	return log;
}

bool Log::OpenLog()
{
	SYSTEMTIME SystemTime;
	GetLocalTime(&SystemTime);
	TCHAR LogFile[MAX_PATH];
       _stprintf(LogFile, _T("test%04d-%02d-%02d.log"), SystemTime.wYear, SystemTime.wMonth, SystemTime.wDay);
  	SharedObjectPtr<Appender>  append(new FileAppender(LogFile, std::ios_base::app));
	append->setName(L"file log test");
	std::wstring pattern = L"%D{%Y/%m/%d-%H:%M:%S}-[%p]-[%b:%L] - %m%n";
	std::auto_ptr<Layout> layout(new PatternLayout(pattern));append->setLayout(layout);
	Log::logger.addAppender(SharedAppenderPtr(append.get()));
	Log::logger.setLogLevel(ALL_LOG_LEVEL);
	return true;
}

**Comment by wilx** [comment] 2018-04-13 05:14
[**@atu5554**](https://github.com/atu5554) commented on [Apr 13, 2018, 3:01 AM GMT+2](https://github.com/log4cplus/log4cplus/issues/306#issuecomment-380988787 "2018-04-13T01:01:00Z - Replied by Github Reply Comments"):
> I use GBK, zh_CN.UTF-8,  zh_CN,  zh_CN.Simplified. 

Please try with the dash as I have shown and not with the underscore. Windows does not recognize the same locale names as Linux does. Also, Windows does not support any UTF-8 locale.

> An exception will occur “std::runtime_error” Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  

This does not make any sense. Do you have a call stack? 

> I use log4cplusD.dll. log4cplusD.lib。 Build prompt “You are not using DLL C run time library.You must call log4cplus::initialize() once before you use any other log4cplus API.”

Please notice the “DLL C run time library” in the message. This refers to the distinction between `MSVCRT.DLL` and `libcmt`, i.e., DLL C run time library and static C run time library.

**Comment by atu5554** [comment] 2018-04-14 07:43
@wilx 
Sorry, it should be the problem of output unicode setting.
 I use narrow character output to record Chinese, wide character output fails. 
But for log4cplus project I have set unicode.
 Do you need to set it to support unicode?

**Comment by wilx** [comment] 2018-04-14 20:42
[**@atu5554**](https://github.com/atu5554) commented on [Apr 14, 2018, 9:43 AM GMT+2](https://github.com/log4cplus/log4cplus/issues/306#issuecomment-381310990 "2018-04-14T07:43:27Z - Replied by Github Reply Comments"):
> @wilx 
> Sorry, it should be the problem of output unicode setting.
>  I use narrow character output to record Chinese, wide character output fails. 
> But for log4cplus project I have set unicode.
>  Do you need to set it to support unicode?

So, if I understand you correctly, you have built log4cplus with Unicode enabled, i.g., the log4cplus API accepts `wchar_t` and `std::wstring`. But you want your files to be in some sort of non-Unicode Chinese capable encoding. Right?

**Comment by wilx** [comment] 2018-04-14 21:44
I have just tested on Windows 10 with Visual Studio 2017 and I get code page 936 output with visibly correct Simplified Chinese characters when I just imbue `FileAppender` with `"zh-CN"` locale when using `Debug_Unicode` configuration. The Visual Studio did warn me and let me save the C++ test source file with Unicode encoding so that the literal `汉语` is correctly preserved during compilation.

If you want to create `FileAppender` that will have UTF-8 encoding then you would have to imbue the appender with modified locale with `codecvt` facet:

```cpp
	append_1->imbue(
		std::locale(append_1->getloc(),
			new std::codecvt_utf8<tchar, 0x10FFFF,
			static_cast<std::codecvt_mode>(std::consume_header | std::little_endian)>));
```

**Comment by atu5554** [comment] 2018-04-16 11:28
Sorry, I use Google Translate and can be not very accurate

**Comment by wilx** [comment] 2018-04-16 11:30
[**@atu5554**](https://github.com/atu5554) commented on [16 Apr 2018, 13:21 CEST](https://github.com/log4cplus/log4cplus/issues/306#issuecomment-381566309 "2018-04-16T11:21:50Z - Replied by Github Reply Comments"):
> Thank you,I added append_1->imbue(),
> such as：
>       1.        LOG4CPLUS_INFO(Log::logger, "汉语" << 123);      Successful output
>        2.   std::string s = "汉语";      LOG4CPLUS_WARN(Log::logger, s);      Successful output     
>        3.std::wstring str = _T("汉语");    LOG4CPLUS_WARN(Log::logger, str);     Output failed
> Can unicode not make std::wstring  succeed?

It works for me somehow.

- What is the actual encoding of the C++ source file?
- What is the code page in your terminal window that you are using to run your test executable?

**Comment by atu5554** [comment] 2018-04-16 11:40
Vs2015 created c++ file, I did not modify its file encoding

**Comment by wilx** [comment] 2018-08-21 17:09
@atu5554 Were you able to solve your problem with Chinese output?

**Comment by atu5554** [comment] 2018-08-24 05:47
I can't, I am working on Linux now, using English output, I will continue to solve the problem after waiting for some time.Now use English output.

**Comment by wilx** [comment] 2019-04-09 17:11
I am closing this since it works for me. I think the issue is somewhere in the combination of sources encoding and locale that is imbued or not during run time.

**Closed by wilx** 2019-04-09 17:11 UTC
Labels: l10n/i18n
