### ISSUE TITLE
a bug in TimeBasedRollingFileAppender?

### ISSUE THREAD

**Issue by elithnever** [log4cplus/log4cplus#84] opened 2015-03-24 01:21 UTC
I am using log4cplus 1.2.0 rc3 now.

When I use `TimeBasedRollingFileAppender`, I find the last file will be empty after the program exits.

And I review the code, line 1213 in `src/fileappender.cxx`  looks like a bug. why do you call `rollover()` function in the `close()` function ? after I comment the code, the last file works.

below is my config, is this a bug or my fault?

~~~~
log4cplus.rootLogger=TRACE, trace

log4cplus.appender.trace=log4cplus::TimeBasedRollingFileAppender
log4cplus.appender.trace.MaxHistory=2
log4cplus.appender.trace.Filename=demo.trace
log4cplus.appender.trace.FilenamePattern=demo.trace.%d{yyyy-MM-dd-HH-mm}
log4cplus.appender.trace.CleanHistoryOnStart=false
log4cplus.appender.trace.filters.1=log4cplus::spi::LogLevelRangeFilter
log4cplus.appender.trace.filters.1.LogLevelMin=TRACE
log4cplus.appender.trace.filters.1.LogLevelMax=DEBUG
log4cplus.appender.trace.filters.1.AcceptOnMatch=true
log4cplus.appender.trace.filters.2=log4cplus::spi::DenyAllFilter
log4cplus.appender.trace.layout=log4cplus::PatternLayout
log4cplus.appender.trace.layout.ConversionPattern=%5p: %D: demo %T [%l] %m%n
~~~~

**Comment by wilx** [comment] 2015-08-02 14:28
I think this is by design. `DailyRollingFileAppender` does the same thing since ever (5b6b25a882a2f385861d5cffd53a5a918c47deb8). `TimeBasedRollingFileAppender` is new and it has inherited the feature from `DailyRollingFileAppender`. The idea is that if you do not roll the file when you are closing the appender, you will not know what file name to use next time you start your application and need to roll it.

**Comment by artur-shaik** [comment] 2015-12-09 12:47
For me, it looks like a bug, too.

```c++
    const char* logPath = logDir.append("%d.log").toStdString().c_str();
    
    initialize();

    helpers::Properties p;
    p.setProperty(LOG4CPLUS_TEXT("FilenamePattern"), LOG4CPLUS_TEXT(logPath));
    p.setProperty(LOG4CPLUS_TEXT("CleanHistoryOnStart"), LOG4CPLUS_TEXT("false"));
    p.setProperty(LOG4CPLUS_TEXT("CreateDirs"), LOG4CPLUS_TEXT("true"));
    p.setProperty(LOG4CPLUS_TEXT("ImmediateFlush"), LOG4CPLUS_TEXT("true"));
    p.setProperty(LOG4CPLUS_TEXT("DatePattern"), LOG4CPLUS_TEXT("yyyy-MM-dd"));

    const char* pattern = "%-7r [%d{%Y/%m%dT%H:%M:%S.%Q}] %5p [%10.10t] %c <> %m%n";
    SharedTimeBasedRollingFileAppenderPtr fileAppender(new TimeBasedRollingFileAppender(p));
    fileAppender->setName(LOG4CPLUS_TEXT("FileAppender"));
    fileAppender->setLayout(std::auto_ptr<Layout>(new PatternLayout(pattern)));
    Logger::getRoot().addAppender(SharedAppenderPtr(fileAppender.get()));

    if (verbose)
    {
        helpers::SharedObjectPtr<Appender> consoleAppender(new ConsoleAppender());
        consoleAppender->setLayout(std::auto_ptr<Layout>(new PatternLayout(pattern)));
        consoleAppender->setName(LOG4CPLUS_TEXT("ConsoleAppender"));
        Logger::getRoot().addAppender(consoleAppender);
    }

    Logger::getRoot().setLogLevel(getLogLevel(level));
```

With this setup, on exit log file always empty.

If I add:
```c++
    p.setProperty(LOG4CPLUS_TEXT("Filename"), LOG4CPLUS_TEXT(filePath));
```
On exit patterned log file is always overwrited. Doesn't append to old log file.

Or may be this is wrong approach?

PS For now I have removed `rollover` call in `close()` method, and it works as expected for me.

**Comment by sangechen** [comment] 2016-01-11 08:49
I had fix this problem using:
1. remove `rollover()` call in `close()` {TimeBasedRollingFileAppender do not need this rollover behavior, I think}
2. after rotate log files, re-open new file, do not `truncate` it!  {when `File` property is missing, TimeBasedRollingFileAppender do not rollover at all. so we cannot truncate any file}

**Comment by wilx** [comment] 2016-01-17 17:40
I think this is now fixed by https://github.com/log4cplus/log4cplus/pull/123.

**Closed by wilx** 2016-01-17 17:40 UTC
Labels: enhancement
